/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fmod_core_FmodUtils */

#ifndef _Included_org_fmod_core_FmodUtils
#define _Included_org_fmod_core_FmodUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fmod_core_FmodUtils
 * Method:    playSound
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_fmod_core_FmodUtils_playSound
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_fmod_core_FmodUtils
 * Method:    pauseSound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fmod_core_FmodUtils_pauseSound
  (JNIEnv *, jclass,jboolean);

/*
 * Class:     org_fmod_core_FmodUtils
 * Method:    stopSound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fmod_core_FmodUtils_stopSound
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
