/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fmod_core_FmodUtils_Effect */

#ifndef _Included_org_fmod_core_FmodUtils_Effect
#define _Included_org_fmod_core_FmodUtils_Effect
#ifdef __cplusplus
extern "C" {
#endif
enum Effect_Mode {
    MODE_ORIGINAL = 0,  //原声
    MODE_LOLITA = 1,  //萝莉
    MODE_UNCLE = 2,  //大叔
    MODE_THRILLER = 3,  //惊悚
    MODE_FUNNY = 4,  //搞怪
    MODE_ETHEREAL = 5,  //空灵
    MODE_DRAWL = 6,   //慢吞吞
    MODE_CHORUS = 7    //合唱
};
#ifdef __cplusplus
}
#endif
#endif
